### ISSUE TITLE
i has big idea for u, pls implement

### ISSUE THREAD

**Issue by bennysolo** [aDu/pet-pet-gif#4]
hello everyone! i has come up with very good idea! my idea is like uber for blockchain, but it is pet-pet-gif on the blockchain! we can decentralise it and then put artificial intelligence and machine learning on it, then i am confident it will become #1 most starred github repo. Also also, can u put quantum computing on it to make it faster to produce the pet pet gifs. we shud also make pet pet gif into its own cryptocurrency (because iirc elon musk one of my best friend said crypto is good i think), so people have to pay in pet pet gif coins before they can make any feature request on github. And can u accept my friend request on league of legends + linkedIn cus i wanna chat to u about some more business we can do and i can handle the business side, i just need some coding, there is no pay but it will be good exposure for ur cv and i will also give u a recommendation too.

my idea summed in a few bullet points:

** insert my juicy idea here in few bullet point, pls dont steal my idea cus i copyright it and i will sue u if u copy, but we split the revenue 50/50 yh? i handle all the marketing for u, just code it pls **

and the problem im trying to solve is:

** insert what the idea will solve, i think it might solve global warming and the financial crisis if we add this idea on the blockchain and make it into an NFT **

Thank u for listening and i hope everyone has a merry christmas, pls implement, pls, i hope u do and if u dont then u r losing big opportunity.

**Comment by aDu** [comment]
Unfortunately, the requirement to have a Feature Request accepted is for the requester to beat me 1v1 on Valorant, on the Haven map - best out of 3. Until then, I'll have to close this request.

Alternatively, 10 BTC can be taken as payment.
